name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  example-basic:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './_example/basic'
  example-complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.5
    with:
      working_directory: './_example/complete'
      